### ISSUE TITLE
How to get short name

### ISSUE THREAD

**Issue by ClearSeve** [mngsk/device-detector#2]
How to get short name

**Comment by mngsk** [comment]
We decided not to include the short codes in the public API because they're not standard, but created by Matomo, and even they are planning to remove them for their next major version.

We advise not to rely upon the short codes, but if you really need them, you could take the `SHORT_BRAND_NAMES` map in the [DeviceMixin](https://github.com/mngsk/device-detector/blob/master/src/test/java/io/github/mngsk/devicedetector/device/DeviceMixin.java) class and invert the keys and values. For the browser's short codes, your best bet is to create a map based on the `$availableBrowsers` array of the PHP [Browser](https://github.com/matomo-org/device-detector/blob/master/Parser/Client/Browser.php) class.

**Comment by ClearSeve** [comment]
Thank you very much for your reply. I wanted to use the icon provided by matomo

**Comment by ClearSeve** [comment]
:)
