### ISSUE TITLE
[FEATURE REQUEST] Update "regexes" list

### ISSUE THREAD

**Issue by WuglyakBolgoink** [mngsk/device-detector#3]
Hallo @mngsk !

Can you do automated update of original regexes from https://github.com/matomo-org/device-detector/tree/master/regexes?

Because matomo updated this list regularly.

**Comment by mngsk** [comment]
The regexes can be easily imported, but in order for all the tests to pass, some manual adjustments are required, at least until matomo get rid of the short codes ([planned for version 4](https://github.com/matomo-org/device-detector/pull/6014)), or at least include them in the regex files instead of having them hard coded.

I've been trying to update the regex files approximately once a month, but I know it might not be sufficient for everybody. If you're interested, I can share the steps I use to do the update, so that you can build a fresh version whenever you want, but mind you, it's a somewhat tedious process.

**Comment by minduch** [comment]
Hi @mngsk

It would be great if you could share how to update the "regexes" list as his code is on version 4.3.0.

All the best and good job!
