### ISSUE TITLE
last version 

### ISSUE THREAD

**Issue by classjing** [mngsk/device-detector#5]
The latest version of Java does not seem to be very accurate, I wonder if it has not been updated.But the latest version of PHP is accurate. Could you update Java as well? Thank you

**Comment by mngsk** [comment]
Thank you for your report. I just updated the fixtures files from the PHP version.

**Comment by classjing** [comment]
Thank you very much. I didn't give you an issue originally, but I replied so quickly. Thank you again for your open source spirit

**Comment by classjing** [comment]
Thank you very much. At present, the test data is relatively accurate. Thanks again for open source, and the reply is very timely

**Comment by classjing** [comment]
I wonder if short_name can be provided in the client, because I see short_name CH,OP,FF in PHP, it would be better if Java had short_name, thank you

**Comment by mngsk** [comment]
As far as I know, short codes are deprecated (or even removed) in the PHP version. See [here](https://github.com/matomo-org/device-detector/pull/6399) and [here](https://github.com/matomo-org/device-detector/pull/6014).

Originally I didn't include the short codes because they're not standard (are invented by committers) and had no use for me; the original PHP version only used them internally. The forks in other languages don't seem to used them either.

It would be very hard for me to include them and maintain them at this point. Sorry.
